#!/usr/bin/env python3
"""
╔══════════════════════════════════════════════════════════════════╗
║  HELL SOCIETY - Termux Compatibility Patch                       ║
║  Created by: HELL SOCIETY Community                              ║
║  Patches all scripts for Termux/Linux compatibility              ║
╚══════════════════════════════════════════════════════════════════╝
"""

import os
import sys
import re
import platform

BANNER = """
╔══════════════════════════════════════════════════════════════════╗
║  HELL SOCIETY - Termux Compatibility Patch v2.0                  ║
╚══════════════════════════════════════════════════════════════════╝
"""

def is_termux():
    """Detect if running on Termux"""
    return ('Android' in platform.system() or
            os.environ.get('PREFIX', '').startswith('/data/data/com.termux'))

def patch_script(filepath):
    """Apply Termux compatibility patches to a script"""
    with open(filepath, 'r') as f:
        content = f.read()

    original = content

    # Patch 1: Replace /tmp/ paths with Termux-compatible paths
    if is_termux():
        tmp_path = os.path.expanduser('~/hell-society/data')
        content = content.replace('/tmp/', tmp_path + '/')
    else:
        tmp_path = '/tmp/'

    # Patch 2: Replace sudo commands for Termux
    content = content.replace("sudo pip3 install", "pip3 install")
    content = content.replace("sudo apt-get", "pkg install")
    content = content.replace("sudo apt", "pkg")

    # Patch 3: Fix subprocess calls for Termux
    content = content.replace("['traceroute'", "['tracepath' if os.environ.get('PREFIX') else 'traceroute'")

    # Save if changed
    if content != original:
        with open(filepath, 'w') as f:
            f.write(content)
        return True
    return False

def main():
    print(BANNER)

    toolkit_dir = os.path.dirname(os.path.abspath(__file__))

    # Scan all Python scripts
    categories = ['offensive', 'defensive', 'osint']
    patched_count = 0

    for category in categories:
        cat_dir = os.path.join(toolkit_dir, category)
        if not os.path.isdir(cat_dir):
            continue

        for filename in sorted(os.listdir(cat_dir)):
            if filename.endswith('.py'):
                filepath = os.path.join(cat_dir, filename)
                if patch_script(filepath):
                    patched_count += 1
                    print(f"  [+] Patched: {category}/{filename}")
                else:
                    print(f"  [OK] No patch needed: {category}/{filename}")

    print(f"\n[+] Patched {patched_count} scripts")

    # Create Termux-specific config
    if is_termux():
        config = """
# HELL SOCIETY - Termux Config
# Auto-generated by compatibility patch

TERMUX = True
PYTHON = "python3"
PREFIX = "/data/data/com.termux/files/usr"
HOME = os.path.expanduser("~")
DATA_DIR = os.path.join(HOME, "hell-society", "data")
RESULTS_DIR = DATA_DIR
"""
        config_path = os.path.join(toolkit_dir, 'termux_config.py')
        with open(config_path, 'w') as f:
            f.write(config)
        print(f"[+] Termux config created: {config_path}")

        # Create data directory
        os.makedirs(os.path.expanduser('~/hell-society/data'), exist_ok=True)
        print(f"[+] Data directory created: ~/hell-society/data/")

    print("\n[+] All scripts are now compatible!")

if __name__ == "__main__":
    main()
