#!/usr/bin/env python3
"""
╔══════════════════════════════════════════════════════════════════╗
║  WAF CONFIGURATION GENERATOR v2.0                                ║
║  Created by: HELL SOCIETY Community                              ║
║  Category: Defensive - Web Application Firewall                  ║
╚══════════════════════════════════════════════════════════════════╝
"""

import sys
import os
import colorama
from colorama import Fore, Back, Style
import argparse

colorama.init(autoreset=True)

BANNER = f"""
{Fore.GREEN}╔══════════════════════════════════════════════════════════════════╗
║{Fore.CYAN}  ██╗    ██╗██╗   ██╗███████╗██╗  ██╗██████╗  █████╗ ███████╗██╗  {Fore.GREEN}║
║{Fore.CYAN}  ██║    ██║██║   ██║██╔════╝██║ ██╔╝██╔══██╗██╔══██╗██╔════╝██║  {Fore.GREEN}║
║{Fore.CYAN}  ██║ █╗ ██║██║   ██║███████╗█████╔╝ ██║  ██║███████║███████╗██║  {Fore.GREEN}║
║{Fore.CYAN}  ██║███╗██║██║   ██║╚════██║██╔═██╗ ██║  ██║██╔══██║╚════██║██║  {Fore.GREEN}║
║{Fore.CYAN}  ╚███╔███╔╝╚██████╔╝███████║██║  ██╗██████╔╝██║  ██║███████║███████{Fore.GREEN}║
║{Fore.CYAN}   ╚══╝╚══╝  ╚═════╝ ╚══════╝╚═╝  ╚═╝╚═════╝ ╚═╝  ╚═╝╚══════╝╚══════{Fore.GREEN}║
╠══════════════════════════════════════════════════════════════════╣
║{Fore.YELLOW}  HELL SOCIETY - WAF Configuration Generator v2.0                     {Fore.GREEN}║
╚══════════════════════════════════════════════════════════════════╝
"""

class WAFGenerator:
    def __init__(self, output_dir):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def generate_nginx_waf(self):
        config = """# HELL SOCIETY WAF Configuration for Nginx
# Generated by Hell Society WAF Generator v2.0

# Rate Limiting
limit_req_zone $binary_remote_addr zone=general:10m rate=10r/s;
limit_req_zone $binary_remote_addr zone=api:10m rate=5r/s;
limit_req_zone $binary_remote_addr zone=login:10m rate=1r/s;

# Block common attack patterns
map $request_uri $block_request {
    default 0;

    # SQL Injection patterns
    ~*"(\\%27)|(\')|(\\%23)|(#)" 1;
    ~*"(union.*select)" 1;
    ~*"(or|and).*[0-9]+\\s*=\\s*[0-9]+" 1;

    # XSS patterns
    ~*"<script" 1;
    ~*"javascript:" 1;
    ~*"on(load|error|click|mouseover)" 1;

    # LFI/RFI patterns
    ~*"\\.\\./" 1;
    ~*"php://filter" 1;
    ~*"php://input" 1;
    ~*"expect://" 1;

    # Command injection
    ~*"[;|&`]" 1;

    # Directory traversal
    ~*"\\.\\.\\/" 1;
}

server {
    listen 80;
    listen 443 ssl http2;

    # Security Headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:;" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;

    # Block suspicious requests
    if ($block_request) {
        return 403;
    }

    # Block specific user agents
    if ($http_user_agent ~* "(nikto|sqlmap|nmap|masscan|dirbuster|gobuster|wfuzz|hydra)") {
        return 403;
    }

    # Rate limiting
    location /api/ {
        limit_req zone=api burst=20 nodelay;
        proxy_pass http://backend;
    }

    location /login {
        limit_req zone=login burst=5 nodelay;
        proxy_pass http://backend;
    }

    location / {
        limit_req zone=general burst=30 nodelay;
        proxy_pass http://backend;
    }

    # Block access to sensitive files
    location ~ /\\.(htaccess|htpasswd|git|svn|env) {
        deny all;
        return 403;
    }

    # Block access to backup files
    location ~ \\.(bak|conf|dist|fla|in[ci]|log|orig|psd|sh|sql|sw[op])$ {
        deny all;
        return 403;
    }

    # SSL Configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256;
    ssl_prefer_server_ciphers on;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_stapling on;
    ssl_stapling_verify on;
}
"""
        filepath = os.path.join(self.output_dir, 'nginx_waf.conf')
        with open(filepath, 'w') as f:
            f.write(config)
        print(f"  {Fore.GREEN}[+] Nginx WAF config: {filepath}")

    def generate_apache_waf(self):
        config = """# HELL SOCIETY WAF Configuration for Apache (mod_security style)
# Generated by Hell Society WAF Generator v2.0

<IfModule mod_headers.c>
    # Security Headers
    Header set X-Frame-Options "SAMEORIGIN"
    Header set X-Content-Type-Options "nosniff"
    Header set X-XSS-Protection "1; mode=block"
    Header set Referrer-Policy "strict-origin-when-cross-origin"
    Header set Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'"
    Header set Strict-Transport-Security "max-age=31536000; includeSubDomains"
    Header set Permissions-Policy "geolocation=(), microphone=(), camera=()"
</IfModule>

# Block SQL Injection
<IfModule mod_rewrite.c>
    RewriteEngine On

    # Block SQL injection attempts
    RewriteCond %{QUERY_STRING} (\\%27)|(\\')|(\\%23)|(#) [NC]
    RewriteRule ^(.*)$ - [F,L]

    RewriteCond %{QUERY_STRING} union.*select [NC]
    RewriteRule ^(.*)$ - [F,L]

    RewriteCond %{QUERY_STRING} (or|and).*[0-9]+\\s*=\\s*[0-9]+ [NC]
    RewriteRule ^(.*)$ - [F,L]

    # Block XSS attempts
    RewriteCond %{QUERY_STRING} <script [NC]
    RewriteRule ^(.*)$ - [F,L]

    RewriteCond %{QUERY_STRING} javascript: [NC]
    RewriteRule ^(.*)$ - [F,L]

    # Block LFI/RFI
    RewriteCond %{QUERY_STRING} \\.\\./ [NC]
    RewriteRule ^(.*)$ - [F,L]

    RewriteCond %{QUERY_STRING} php://filter [NC]
    RewriteRule ^(.*)$ - [F,L]

    # Block command injection
    RewriteCond %{QUERY_STRING} [;|&`] [NC]
    RewriteRule ^(.*)$ - [F,L]

    # Block directory traversal
    RewriteCond %{REQUEST_URI} \\.\\./ [NC]
    RewriteRule ^(.*)$ - [F,L]

    # Block user agents
    RewriteCond %{HTTP_USER_AGENT} (nikto|sqlmap|nmap|dirbuster|gobuster) [NC]
    RewriteRule ^(.*)$ - [F,L]
</IfModule>

# Block access to sensitive files
<FilesMatch "\\.(htaccess|htpasswd|git|svn|env|bak|sql|conf)$">
    Require all denied
</FilesMatch>

# SSL Configuration
SSLEngine on
SSLProtocol all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
SSLHonorCipherOrder on
SSLCipherSuite ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256
SSLCompression off
SSLSessionTickets off
"""
        filepath = os.path.join(self.output_dir, 'apache_waf.conf')
        with open(filepath, 'w') as f:
            f.write(config)
        print(f"  {Fore.GREEN}[+] Apache WAF config: {filepath}")

    def generate_modsecurity(self):
        config = """# HELL SOCIETY ModSecurity Rules
# Generated by Hell Society WAF Generator v2.0

SecRuleEngine On
SecRequestBodyAccess On
SecResponseBodyAccess On

# Audit logging
SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
SecAuditLogParts ABIJDEFHZ
SecAuditLogType Serial
SecAuditLog /var/log/modsec_audit.log

# SQL Injection Rules
SecRule ARGS "@rx (?i:(\\bselect\\b.{1,100}?\\bfrom\\b))" "id:1001,phase:2,t:none,t:urlDecodeUni,block,msg:'SQL Injection Detected'"
SecRule ARGS "@rx (?i:(\\bunion\\b.{1,100}?\\bselect\\b))" "id:1002,phase:2,t:none,t:urlDecodeUni,block,msg:'SQL Injection UNION'"
SecRule ARGS "@rx (?i:(\\bor\\b.{1,100}?[0-9]+\\s*=\\s*[0-9]+))" "id:1003,phase:2,t:none,block,msg:'SQL Injection OR'"
SecRule ARGS "@rx (?i:(\\bdrop\\b.{1,100}?\\btable\\b))" "id:1004,phase:2,t:none,block,msg:'SQL Injection DROP'"

# XSS Rules
SecRule ARGS "@rx (?i:(<script.*?>))" "id:2001,phase:2,t:none,t:urlDecodeUni,block,msg:'XSS Detected'"
SecRule ARGS "@rx (?i:(javascript\\s*:))" "id:2002,phase:2,t:none,t:urlDecodeUni,block,msg:'XSS JavaScript Protocol'"
SecRule ARGS "@rx (?i:(on(load|error|click|mouseover|focus|blur)\\s*=))" "id:2003,phase:2,t:none,block,msg:'XSS Event Handler'"
SecRule ARGS "@rx (?i:(<img[^>]+onerror\\s*=))" "id:2004,phase:2,t:none,block,msg:'XSS Image Tag'"

# LFI/RFI Rules
SecRule ARGS "@rx (?i:(\\.\\./))" "id:3001,phase:2,t:none,block,msg:'LFI Detected'"
SecRule ARGS "@rx (?i:(php://filter))" "id:3002,phase:2,t:none,block,msg:'PHP Filter LFI'"
SecRule ARGS "@rx (?i:(php://input))" "id:3003,phase:2,t:none,block,msg:'PHP Input Injection'"
SecRule ARGS "@rx (?i:(expect://))" "id:3004,phase:2,t:none,block,msg:'Expect Protocol'"

# Command Injection Rules
SecRule ARGS "@rx (?i:([;|&`]))" "id:4001,phase:2,t:none,block,msg:'Command Injection'"
SecRule ARGS "@rx (?i:(\\$\\(.*\\)))" "id:4002,phase:2,t:none,block,msg:'Command Substitution'"

# Rate Limiting
SecAction "id:5001,phase:1,nolog,pass,initcol:ip=%{REMOTE_ADDR},setvar:ip.global_counter=+1,expirevar:ip.global_counter=60"
SecRule IP:GLOBAL_COUNTER "@gt 60" "id:5002,phase:1,deny,status:429,msg:'Rate Limit Exceeded'"

# Block scanning tools
SecRule REQUEST_HEADERS:User-Agent "@rx (?i:(nikto|sqlmap|nmap|dirbuster|gobuster|wfuzz|hydra))" "id:6001,phase:1,deny,status:403,msg:'Scanning Tool Detected'"
"""
        filepath = os.path.join(self.output_dir, 'modsecurity_rules.conf')
        with open(filepath, 'w') as f:
            f.write(config)
        print(f"  {Fore.GREEN}[+] ModSecurity rules: {filepath}")

    def generate_all(self):
        print(f"{Fore.CYAN}  [*] Output directory: {Fore.WHITE}{self.output_dir}\n")
        self.generate_nginx_waf()
        self.generate_apache_waf()
        self.generate_modsecurity()
        print(f"\n{Fore.GREEN}[OK] All WAF configurations generated successfully!")

def main():
    print(BANNER)

    parser = argparse.ArgumentParser(description='Hell Society WAF Generator')
    parser.add_argument('-o', '--output', default='/home/ubuntu/waf_config', help='Output directory')
    args = parser.parse_args()

    generator = WAFGenerator(args.output)
    generator.generate_all()

if __name__ == "__main__":
    main()
